In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow .keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense

In [5]:
max_features=10000
(X_train,y_train),(X_test,y_test)=imdb.load_data(num_words=max_features)
print("Training data shape",X_train.shape,"Training labels shape",y_train.shape)
print("Training data shape",X_test.shape,"Training labels shape",y_test.shape)


Training data shape (25000,) Training labels shape (25000,)
Training data shape (25000,) Training labels shape (25000,)


In [7]:
sample_review=X_train[0]
sample_label=y_train[0]
print("Review",sample_review)
print("Label",sample_label)


Review [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]
Label 1


In [8]:
word_index=imdb.get_word_index()
reverse_word_index={value:key for key , value in word_index.items()}
reverse_word_index

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


{34701: 'fawn',
 52006: 'tsukino',
 52007: 'nunnery',
 16816: 'sonja',
 63951: 'vani',
 1408: 'woods',
 16115: 'spiders',
 2345: 'hanging',
 2289: 'woody',
 52008: 'trawling',
 52009: "hold's",
 11307: 'comically',
 40830: 'localized',
 30568: 'disobeying',
 52010: "'royale",
 40831: "harpo's",
 52011: 'canet',
 19313: 'aileen',
 52012: 'acurately',
 52013: "diplomat's",
 25242: 'rickman',
 6746: 'arranged',
 52014: 'rumbustious',
 52015: 'familiarness',
 52016: "spider'",
 68804: 'hahahah',
 52017: "wood'",
 40833: 'transvestism',
 34702: "hangin'",
 2338: 'bringing',
 40834: 'seamier',
 34703: 'wooded',
 52018: 'bravora',
 16817: 'grueling',
 1636: 'wooden',
 16818: 'wednesday',
 52019: "'prix",
 34704: 'altagracia',
 52020: 'circuitry',
 11585: 'crotch',
 57766: 'busybody',
 52021: "tart'n'tangy",
 14129: 'burgade',
 52023: 'thrace',
 11038: "tom's",
 52025: 'snuggles',
 29114: 'francesco',
 52027: 'complainers',
 52125: 'templarios',
 40835: '272',
 52028: '273',
 52130: 'zaniacs',

In [10]:
decoded_review=' '.join([reverse_word_index.get(i -3,'?')for i in sample_review])
decoded_review


"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [11]:
from tensorflow.keras.preprocessing import sequence
max_len=500
X_train=sequence.pad_sequences(X_train,maxlen=max_len)
X_test=sequence.pad_sequences(X_test,maxlen=max_len)
X_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [12]:
X_train[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [17]:
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN, Dense

model = Sequential()
model.add(Embedding(input_dim=max_features, output_dim=128, input_length=max_len))
model.add(SimpleRNN(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


In [20]:
model.build(input_shape=(None, max_len))
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 500, 128)       │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_3 (SimpleRNN)        │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,313,025 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [24]:
from tensorflow.keras.callbacks import EarlyStopping
earlystopping=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)
earlystopping

In [25]:
history=model.fit(X_train,y_train,epochs=10,batch_size=32,validation_split=0.2,
                  callbacks=[earlystopping])

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 152s 241ms/step - accuracy: 0.6069 - loss: 25.3241 - val_accuracy: 0.7916 - val_loss: 0.4559
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 200s 238ms/step - accuracy: 0.8372 - loss: 0.3887 - val_accuracy: 0.8168 - val_loss: 0.4442
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 205s 243ms/step - accuracy: 0.8488 - loss: 0.3617 - val_accuracy: 0.7742 - val_loss: 0.4726
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 200s 240ms/step - accuracy: 0.8801 - loss: 4.8453 - val_accuracy: 0.8196 - val_loss: 0.4341
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 200s 236ms/step - accuracy: 0.9255 - loss: 0.1964 - val_accuracy: 0.8138 - val_loss: 0.4630
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 148s 236ms/step - accuracy: 0.9434 - loss: 0.1603 - val_accuracy: 0.7608 - val_loss: 0.5266
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 201s 234ms/step - accuracy: 0.9349 - loss: 0.1815 - val_accuracy: 0.8104 - val_loss: 0.5364
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 201s 234ms/step - accuracy: 0.9568 

In [26]:
model.save('movie_review_rnn.h5')

In [27]:
# PREDICTION

In [29]:
from tensorflow.keras.models import load_model
model=load_model('movie_review_rnn.h5')
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 500, 128)       │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_3 (SimpleRNN)        │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,313,027 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [30]:
model.get_weights()

[array([[-0.43610546,  0.25388575, -0.20034562, ..., -0.71954936,
          0.22159195,  0.27876025],
        [ 0.03949206,  0.05248605,  0.04694926, ..., -0.0076122 ,
          0.00974926, -0.01929159],
        [ 0.07109297,  0.04195451,  0.09265504, ..., -0.13261366,
          0.06783506, -0.01212051],
        ...,
        [-0.04378995,  0.07742545, -0.00510951, ...,  0.00864233,
         -0.02655635, -0.03321741],
        [ 0.10981715, -0.08454374,  0.04112449, ...,  0.13786091,
         -0.091801  , -0.03497151],
        [-0.10248664,  0.04721433, -0.08967607, ...,  0.00860281,
          0.12534067, -0.01563958]], dtype=float32),
 array([[ 0.11465895, -0.01597685,  0.16344184, ...,  0.06511701,
         -0.13618648,  0.21365142],
        [ 0.08236253, -0.12559952,  0.08048075, ...,  0.10812505,
         -0.08959144, -0.08098912],
        [ 0.10693505, -0.09723365, -0.00202007, ...,  0.11497646,
         -0.08585232, -0.00704438],
        ...,
        [ 0.07417685,  0.07360716, -0.0

In [31]:
def decode_review(encoded_review):
  return ' '.join([reverse_word_index.get(i -3,'?')for i in encoded_review])
def preprocess_text(text):
  words=text.lower().split()
  encoded_review=[word_index.get(word,2)+3 for word in words]
  padded_review=sequence.pad_sequences([encoded_review],maxlen=500)
  return padded_review


In [32]:
def predict_sentiment(review):
  preprocessed_input=preprocess_text(review)
  prediction=model.predict(preprocessed_input)
  sentiment='Positive' if prediction[0][0]>0.5 else 'Negative'
  return sentiment , prediction[0][0]


In [34]:
example="This movie was fantastic"
sentiment,score=predict_sentiment(example)
print("Review",example)
print("Sentiment",sentiment)
print("Prediction Score",score)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
Review This movie was fantastic
Sentiment Positive
Prediction Score 1.0
